name: MCRolePlay
version: 0.7
author: elc1798
main: me.kunai.mcroleplay.MCRolePlay
api-version: 1.16
commands:
  mcrp_augment_item:
    description: Augments the held item with a new enchantment
  mcrp_transmute_item:
    description: Transmutes an item
  mcrp_levelup:
    description: Handles level up
  mcrp_grant_level:
    description: Gives a player a skill point
  mcrp_show_level_data:
    description: Show the player their level data
  mcrp_reload_world:
    description: Reload the world. Optionally provide a relative path to a JSON file relative to plugins/MCRolePlaying
  mcrp_game_state:
    description: Handles commands that read and modify game state
